# Generated by Django 5.1.1 on 2024-10-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_csvtablesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
